service: web-check-api

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

custom:
  webpack:
    webpackConfig: 'api/_common/aws-webpack.config.js'
    includeModules: false
    packagerOptions:
      noInstall: true 

  # customDomain:
  #   domainName: example.com
  #   basePath: 'api'
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true

  # serverless-offline:
  #   prefix: ''
  #   httpPort: 3000

environment:
  GOOGLE_CLOUD_API_KEY: ${ssm:GOOGLE_CLOUD_API_KEY~true, ''}
  TORRENT_IP_API_KEY: ${ssm:TORRENT_IP_API_KEY~true, ''}
  SECURITY_TRAILS_API_KEY: ${ssm:SECURITY_TRAILS_API_KEY~true, ''}
  BUILT_WITH_API_KEY: ${ssm:BUILT_WITH_API_KEY~true, ''}
  URL_SCAN_API_KEY: ${ssm:URL_SCAN_API_KEY~true, ''}
  TRANCO_USERNAME: ${ssm:TRANCO_USERNAME~true, ''}
  TRANCO_API_KEY: ${ssm:TRANCO_API_KEY~true, ''}
  CLOUDMERSIVE_API_KEY: ${ssm:CLOUDMERSIVE_API_KEY~true, ''}
  CHROME_PATH: ${ssm:CHROME_PATH~true, ''}
  API_TIMEOUT_LIMIT: ${ssm:API_TIMEOUT_LIMIT~true, ''}
  API_CORS_ORIGIN: ${ssm:API_CORS_ORIGIN~true, ''}

iamRoleStatements:
  - Effect: Allow
    Action:
      - ssm:GetParameter
    Resource:
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/GOOGLE_CLOUD_API_KEY
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/TORRENT_IP_API_KEY
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/SECURITY_TRAILS_API_KEY
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/BUILT_WITH_API_KEY
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/URL_SCAN_API_KEY
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/TRANCO_USERNAME
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/TRANCO_API_KEY
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/CLOUDMERSIVE_API_KEY
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/CHROME_PATH
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/API_TIMEOUT_LIMIT
      - arn:aws:ssm:us-east-1:${env:AWS_ACCOUNT_ID}:parameter/API_CORS_ORIGIN

functions:
  archives:
    handler: api/archives.handler
    events:
      - http:
          path: api/archives
          method: get
  blockLists:
    handler: api/block-lists.handler
    events:
      - http:
          path: api/block-lists
          method: get
  carbon:
    handler: api/carbon.handler
    events:
      - http:
          path: api/carbon
          method: get
  # ... other functions

plugins:
  - serverless-webpack
  # - serverless-domain-manager
  # - serverless-offline
